[package]
name = "remap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libhelium = "0.1.0"
paste = "1.0.14"
# pretty_env_logger = "0.5.0"
# tracing = "0.1.40"
