name: Rust

on:
  push:
  pull_request:

jobs:
  rust:
    uses: FyraLabs/actions/.github/workflows/rust.yml@main
    with:
      test-container: '{"image": "ghcr.io/terrapkg/builder:f40"}'
      test-pre: |
        dnf5 install -y libhelium-devel tar rustup gcc
        # I'm not sure why setting up Fedora's rustup makes it work, but it does
        rustup-init -y
        echo "PATH=$HOME/.cargo/bin:$PATH" >> $GITHUB_ENV
